autoguru-au/overdrive

- .storybook/config.js
- .travis.yml
- package.json
- readme.md
- yarn.lock
With this PR, we're adding Chromatic screenshot testing - allowing us to ensure that all visual changes in pull requests must be approved before being merged.
> feat: adds chromatic

- lib/components/Button/Button.spec.jsx
- lib/components/Button/Button.tsx
- lib/components/Button/__snapshots__/Button.spec.jsx.snap
- lib/components/Button/stories.tsx
- lib/components/Button/style.scss
- lib/components/ProgressSpinner/ProgressSpinner.tsx
- lib/components/ProgressSpinner/__snapshots__/ProgressSpinner.spec.jsx.snap
- lib/components/ProgressSpinner/style.scss
- lib/components/SimplePagination/__snapshots__/SimplePagination.spec.jsx.snap
Adding a `isLoading` prop to the button, to give it a spinner.
```jsx
<Button isLoading>
Hello World
</Button>
```
> feat(Button): adds a loading state/prop

- lib/components/DateInput/stories.tsx
- lib/components/DetailText/stories.tsx
- lib/components/Heading/stories.tsx
- lib/components/InputBase/NotchedBase.tsx
- lib/components/NumberInput/stories.tsx
- lib/components/SelectInput/stories.tsx
- lib/components/TextAreaInput/stories.tsx
- lib/components/TextInput/stories.tsx
With this PR we hope to allow chromatic to not report changes for random width things, and offsetWidth's that get detected at sudo random times.
> chore: chromatic to ignore stories that don't repeat

- lib/components/DateInput/__snapshots__/DateInput.spec.jsx.snap
- lib/components/InputBase/NotchedBase.spec.jsx
- lib/components/InputBase/NotchedBase.tsx
- lib/components/InputBase/__snapshots__/NotchedBase.spec.jsx.snap
- lib/components/NumberInput/NumberInput.spec.jsx
- lib/components/NumberInput/__snapshots__/NumberInput.spec.jsx.snap
- lib/components/SelectInput/SelectInput.spec.jsx
- lib/components/TextAreaInput/TextAreaInput.spec.jsx
- lib/components/TextAreaInput/__snapshots__/TextAreaInput.spec.jsx.snap
- lib/components/TextInput/TextInput.spec.jsx
- lib/components/TextInput/__snapshots__/TextInput.spec.jsx.snap
With this PR, we aim to "guess" the width of the placeholder, so we don't render the effect of a ~strikethrough~, until we calculate the width of the placeholder.
> refactor(NotchedBase): Default width for the gap, when !isEmpty

- lib/components/InputBase/style.scss
With this PR I aim to align inputs' box shadow with that from our designer.
> feat(InputBase): Applies the z2 box shadow

- lib/components/Button/style.scss
With this PR, I aim to improve the box shadow on Buttons, and allow them to feel more like a button.
> feat(Button): Feel more like a buttons

- lib/components/Pagination/Pagination.spec.jsx
- lib/components/Pagination/Pagination.tsx
- lib/components/Pagination/style.scss
`Button` tags are more appropriate for the left/right buttons. Plus the addition of aria tags.
> feat(Pagination): Suitable aria tags applied

- lib/components/DateInput/stories.tsx
- lib/components/InputBase/style.scss
- lib/components/InputBase/withEnhancedInput.tsx
- lib/components/NumberInput/stories.tsx
- lib/components/SelectInput/stories.tsx
- lib/components/TextAreaInput/stories.tsx
- lib/components/TextInput/stories.tsx
The disabled prop was always there, this time we actually style it.
> feat(InputBase): Styled disabled inputs

- lib/components/Flyout/Flyout.tsx
- lib/components/Flyout/index.ts
- lib/components/Flyout/stories.tsx
- lib/components/Flyout/style.scss
- lib/components/index.ts
This PR is intended to act as the design system'd component for flyout things, to have a consistent background, border and interaction eventually.
Looking for some feedback - maybe this belongs in consumer land? And quite simply just use <Positioner>.
>  feat(Flyout): Initial impl of the Flyout component 

- lib/components/Anchor/Anchor.tsx
- lib/components/Anchor/__snapshots__/Anchor.spec.jsx.snap
- lib/components/Anchor/stories.tsx
- lib/components/Button/Button.tsx
- lib/components/CheckBox/CheckBox.tsx
- lib/components/Icon/Icon.spec.jsx
- lib/components/Icon/Icon.tsx
- lib/components/Icon/index.ts
- lib/components/Icon/stories.tsx
- lib/components/Meta/Meta.spec.jsx
- lib/components/Meta/Meta.tsx
- lib/components/Meta/__snapshots__/Meta.spec.jsx.snap
- lib/components/SelectInput/__snapshots__/SelectInput.spec.jsx.snap
- lib/components/StarRating/StarRating.tsx
- lib/icons/AccountBox.tsx
- lib/icons/Alert.tsx
- lib/icons/ArrowLeft.tsx
- lib/icons/Calendar.tsx
- lib/icons/Check.tsx
- lib/icons/ChevronDown.tsx
- lib/icons/ChevronLeft.tsx
- lib/icons/ChevronRight.tsx
- lib/icons/Minus.tsx
- lib/icons/Phone.tsx
- lib/icons/Plus.tsx
- lib/icons/Star.tsx
- lib/icons/StarHalf.tsx
- lib/icons/WindowClose.tsx
- lib/icons/index.ts
- scripts/buildIcons.js
All Icons are now typed, and is now a `ReactElement`
> feat(Icons): Icons are typed and components rationalized

- lib/components/BulletList/BulletList.scss
- lib/components/BulletList/BulletList.spec.jsx
- lib/components/BulletList/BulletList.tsx
- lib/components/BulletList/__snapshots__/BulletList.spec.jsx.snap
This will align the child ul with the parent li, and the root ul will only now have the padding.
> fix(BulletList): Increase density to align with parent li

- lib/components/Actions/Actions.scss
- lib/components/Actions/Actions.spec.jsx
- lib/components/Actions/Actions.tsx
- lib/components/Actions/__snapshots__/Actions.spec.jsx.snap
- lib/components/Actions/index.ts
- lib/components/Actions/stories.tsx
With this component I aim to add a wrapping component around buttons so we can treat them as a group of buttons (but not be a ButtonGroup, that component will come later 🕺).
> feat(Actions): Init impl of the Actions component

- lib/components/Typography/Text/Text.tsx
- lib/components/Typography/Text/stories.tsx
- lib/components/Typography/TextLink/TextLink.scss
- lib/components/Typography/TextLink/TextLink.spec.jsx
- lib/components/Typography/TextLink/TextLink.tsx
- lib/components/Typography/TextLink/__snapshots__/TextLink.spec.jsx.snap
- lib/components/Typography/TextLink/index.ts
- lib/components/Typography/TextLink/stories.tsx
- lib/components/Typography/index.ts
- lib/components/index.ts
With this PR I aim to add an styled component for inline anchors. Mainly used in block of text, but could also be used standalone.
> feat(TextLink): Init impl of a TextLink component

- lib/theme/tokens/_screen.scss
We should probably have a few breakpoints for our tablets.
> feat: Addition of new screensizes

- lib/components/Alert/Alert.scss
- lib/components/Alert/Alert.spec.jsx
- lib/components/Alert/Alert.tsx
- lib/components/Alert/__snapshots__/Alert.spec.jsx.snap
- lib/components/Alert/stories.tsx
I aim to add inline props, to basically just reduce the elevation - plus allow a non-dismissable prop to remove the close button.
> feat(Alert): Inline and non-dismissible props

- lib/components/ProgressSpinner/style.scss
This PR changes spinner layout from absolutely positioned svg into a more adaptive grid based one
> feat(ProgressSpinner): Updates spinner layout use css grid

- lib/components/DateInput/DateInput.spec.jsx
- lib/components/DateInput/__snapshots__/DateInput.spec.jsx.snap
- lib/components/InputBase/withEnhancedInput.tsx
- lib/components/Positioner/Positioner.tsx
- lib/components/TextInput/stories.tsx
- Function Component instead of class component
- Fixes the unit tests for positioner not running under jest
> feat(withEnhancedInput): Forward Ref to the underlying input

- lib/components/Anchor/Anchor.spec.jsx
- lib/components/Anchor/Anchor.tsx
- lib/components/Badge/Badge.tsx
- lib/components/StarRating/StarRating.tsx
I aim to remove all deprecation warnings - think it's time.
> I've already gone through all internals, and think this is an okay merge.
> feat: Removes all deprecation warnings

- lib/components/AutoSuggest/AutoSuggest.tsx
This PR aims to fix prefocused fullscreen mobile autosuggest option.
> fix: Fixes prefocused mobile autosuggest option

- .playroom/frame.tsx
- .storybook/Wrapper.tsx
- .storybook/config.js
- lib/components/Alert/Alert.treat.ts
- lib/components/Badge/Badge.tsx
- lib/components/Badge/__snapshots__/Badge.spec.jsx.snap
- lib/components/Box/useBoxStyles.treat.ts
- lib/components/Box/useBoxStyles.ts
- lib/components/Columns/Column.treat.ts
- lib/components/Columns/Column.tsx
- lib/components/Columns/Columns.treat.ts
- lib/components/Icon/Icon.treat.ts
- lib/components/Icon/Icon.tsx
- lib/components/Stack/Stack.treat.ts
- lib/components/Typography/Text/useTextStyles.treat.ts
- lib/hooks/useMedia/useMedia.ts
- package.json
- playroom.config.js
- readme.md
- yarn.lock
With this PR I aim to introduce Playroom into our development environment. It really aims to help us experiment and have a play-room to toy our with out components in an easy fashion - before we ship.
There are a few holes in this for now, but we can fix that as time progresses. Like:
- All enums, hooks and HoC's alike all act as components
- No prod build we can consume for now.
> chore: Introduces playroom

- .github/workflows/ci.yml
- .gitignore
- scripts/githubPostPreviewLink.js
Uploads our things to surge.
```
/ => storybook
/playroom => playroom
```
> feat: Deploy sites to surge

- .changeset/spotty-phones-explode.md
- lib/hooks/useNegativeMargin/useNegativeMarginLeft.treat.ts
This aims to fix Column component not completely filling its parent due to negative margins
> feat: Columns width fix

- .changeset/tender-lobsters-watch.md
- lib/components/DateInput/__snapshots__/DateInput.spec.jsx.snap
- lib/components/InputBase/withEnhancedInput.tsx
- lib/components/NumberInput/__snapshots__/NumberInput.spec.jsx.snap
- lib/components/SelectInput/__snapshots__/SelectInput.spec.jsx.snap
- lib/components/TextAreaInput/__snapshots__/TextAreaInput.spec.jsx.snap
- lib/components/TextInput/__snapshots__/TextInput.spec.jsx.snap
InputBase: Always full width the input wrapper
> feat(InputBase): Inputs to always full width

- .changeset/swift-dragons-arrive.md
- lib/components/Tabs/Tabs.tsx
- lib/components/Tabs/__snapshots__/Tabs.spec.jsx.snap
- package.json
Tabs component currently does not fill it's parent when inside a display flex context. This PR will allow explicit width value to be set if needed
> feat: expose box width property in tabs

- .changeset/silent-eels-beg.md
- lib/components/Stack/Stack.tsx
Stack: Expose the Box width on Stack
> feat(Stack): Expose the Box width prop

- .changeset/eighty-swans-nail.md
- lib/components/Tabs/Tab.treat.ts
- lib/components/Tabs/TabList.treat.ts
- lib/components/Tabs/TabList.tsx
- lib/components/Tabs/__snapshots__/Tabs.spec.jsx.snap
Long and short story is that you cannot import treat inside another treat file.
Reference:
- https://github.com/seek-oss/treat/issues/84
> fix: Incorrectly importing treat inside of treat

- .changeset/mighty-lies-brake.md
- lib/components/Inline/Inline.spec.jsx
- lib/components/Inline/Inline.treat.ts
- lib/components/Inline/Inline.tsx
- lib/components/Inline/__snapshots__/Inline.spec.jsx.snap
- lib/components/Inline/stories.tsx
Inline: Supports inline dividers between elements.
Supports, text, numbers, elements or components.
**FEATURES**
```jsx
<Inline dividers>
<Text>Mazda</Text>
<Text>CX3</Text>
<Text>Petrol</Text>
<Text>2020</Text>
</Inline>
```
> feat(Inline): Supports dividers between inline elements

- .changeset/unlucky-vans-smoke.md
- lib/components/Alert/__snapshots__/Alert.spec.jsx.snap
- lib/components/BulletText/__snapshots__/BulletText.spec.jsx.snap
- lib/components/CheckBox/__snapshots__/CheckBox.spec.jsx.snap
- lib/components/DateInput/__snapshots__/DateInput.spec.jsx.snap
- lib/components/Icon/Icon.tsx
- lib/components/Icon/__snapshots__/Icon.spec.jsx.snap
- lib/components/Meta/__snapshots__/Meta.spec.jsx.snap
- lib/components/NumberInput/__snapshots__/NumberInput.spec.jsx.snap
- lib/components/Pagination/__snapshots__/Pagination.spec.jsx.snap
- lib/components/SelectInput/__snapshots__/SelectInput.spec.jsx.snap
- lib/components/SimplePagination/__snapshots__/SimplePagination.spec.jsx.snap
- lib/components/StandardModal/__snapshots__/StandardModal.spec.jsx.snap
- lib/components/Stepper/__snapshots__/Stepper.spec.jsx.snap
- lib/components/TextInput/__snapshots__/TextInput.spec.jsx.snap
- lib/components/Typography/Anchor/__snapshots__/Anchor.spec.jsx.snap
Icon: Child svg's are cloned and positioned to the size of the parent
> feat(Icon): Style child svg's properly

- .changeset/eight-poets-listen.md
- packages/overdrive/lib/components/Alert/__snapshots__/Alert.spec.jsx.snap
- packages/overdrive/lib/components/Anchor/__snapshots__/Anchor.spec.jsx.snap
- packages/overdrive/lib/components/Badge/__snapshots__/Badge.spec.jsx.snap
- packages/overdrive/lib/components/Box/Box.tsx
- packages/overdrive/lib/components/Box/useBoxStyles.ts
- packages/overdrive/lib/components/BulletText/__snapshots__/BulletText.spec.jsx.snap
- packages/overdrive/lib/components/Button/__snapshots__/Button.spec.jsx.snap
- packages/overdrive/lib/components/CheckBox/__snapshots__/CheckBox.spec.jsx.snap
- packages/overdrive/lib/components/DateInput/__snapshots__/DateInput.spec.jsx.snap
- packages/overdrive/lib/components/Inline/__snapshots__/Inline.spec.jsx.snap
- packages/overdrive/lib/components/Meta/__snapshots__/Meta.spec.jsx.snap
- packages/overdrive/lib/components/NumberInput/__snapshots__/NumberInput.spec.jsx.snap
- packages/overdrive/lib/components/Pagination/__snapshots__/Pagination.spec.jsx.snap
- packages/overdrive/lib/components/ProgressBarGroup/__snapshots__/ProgressBarGroup.spec.jsx.snap
- packages/overdrive/lib/components/Radio/__snapshots__/Radio.spec.jsx.snap
- packages/overdrive/lib/components/SelectInput/__snapshots__/SelectInput.spec.jsx.snap
- packages/overdrive/lib/components/SimplePagination/__snapshots__/SimplePagination.spec.jsx.snap
- packages/overdrive/lib/components/StandardModal/__snapshots__/StandardModal.spec.jsx.snap
- packages/overdrive/lib/components/Stepper/__snapshots__/Stepper.spec.jsx.snap
- packages/overdrive/lib/components/Switch/__snapshots__/Switch.spec.jsx.snap
- packages/overdrive/lib/components/Table/__snapshots__/Table.spec.js.snap
- packages/overdrive/lib/components/Tabs/__snapshots__/Tabs.spec.jsx.snap
- packages/overdrive/lib/components/TextAreaInput/__snapshots__/TextAreaInput.spec.jsx.snap
- packages/overdrive/lib/components/TextInput/__snapshots__/TextInput.spec.jsx.snap
- packages/overdrive/lib/components/TextLink/__snapshots__/TextLink.spec.jsx.snap
- packages/overdrive/lib/components/Tooltip/__snapshots__/Tooltip.spec.jsx.snap
- packages/overdrive/lib/components/private/InputBase/__snapshots__/HintText.spec.jsx.snap
- packages/overdrive/lib/components/private/InputBase/__snapshots__/NotchedBase.spec.jsx.snap
Allow non-intrinsics as Box `is` prop as well. With this change you can
send things in like `svg`'s, or other components themselves.
> feat(Box): Allows sending in non-intrinsics

- .changeset/fuzzy-boxes-glow.md
- .changeset/smooth-vans-laugh.md
- packages/overdrive/lib/components/Box/Box.tsx
- packages/overdrive/lib/components/Box/useBoxStyles.treat.ts
- packages/overdrive/lib/components/Box/useBoxStyles.ts
- packages/overdrive/lib/components/Modal/Modal.treat.ts
- packages/overdrive/lib/components/Modal/Modal.tsx
- packages/overdrive/lib/components/Modal/__snapshots__/Modal.spec.jsx.snap
- packages/overdrive/lib/components/StandardModal/__snapshots__/StandardModal.spec.jsx.snap
- packages/overdrive/package.json
- yarn.lock
Adds in a focus trap to our modals + fixes some react concurrent issues with state setting
> feat: Modal concurrent mode fixes + box changes

- .changeset/eight-plants-rule.md
- packages/overdrive/lib/components/AutoSuggest/AutoSuggest.tsx
- packages/overdrive/lib/components/CheckBox/CheckBox.spec.jsx
- packages/overdrive/lib/components/CheckBox/__snapshots__/CheckBox.spec.jsx.snap
- packages/overdrive/lib/components/StarRating/StarRating.tsx
- packages/overdrive/lib/components/private/CheckableBase/CheckableBase.treat.ts
- packages/overdrive/lib/components/private/CheckableBase/CheckableBase.tsx
> feat: Reduces opacity of Checkbox and radio when disabled

- .github/workflows/buildStorybook.yml
This pull request introduces the 'buildStorybook' action, streamlining the generation process of the Storybook for easy component visualization and testing.
> feat: Add buildStorybook action

- .github/workflows/ci.yml
- packages/overdrive/readme.md
- Remove deployment step for storybook in ci.yml because now we have a buildStorybook.yml
- Update Storybook playground URL in readme
> feat: Remove deployment step for storybook in ci.yml

- .changeset/fluffy-singers-sneeze.md
- packages/overdrive/lib/components/Icon/Icon.tsx
- packages/overdrive/lib/components/Icon/stories.tsx
- packages/overdrive/lib/hooks/index.ts
- packages/overdrive/lib/hooks/useNullCheck/index.ts
- packages/overdrive/lib/hooks/useNullCheck/useNullCheck.ts
> feat: Icons warn when passed empty icons in instead of throwing

- .changeset/late-pumas-shout.md
- packages/overdrive/lib/components/NumberInput/NumberInput.tsx
- packages/overdrive/lib/components/NumberInput/__snapshots__/NumberInput.spec.jsx.snap
- packages/overdrive/lib/components/NumberInput/stories.tsx
- packages/overdrive/lib/components/TextAreaInput/TextAreaInput.tsx
- packages/overdrive/lib/components/TextAreaInput/__snapshots__/TextAreaInput.spec.jsx.snap
- packages/overdrive/lib/components/TextAreaInput/stories.tsx
- packages/overdrive/lib/components/TextInput/TextInput.tsx
- packages/overdrive/lib/components/TextInput/__snapshots__/TextInput.spec.jsx.snap
- packages/overdrive/lib/components/TextInput/stories.tsx
> feat: Cap Input text, textarea and numbers

- .changeset/five-otters-trade.md
- lib/components/Alert/__snapshots__/Alert.spec.jsx.snap
- lib/components/Anchor/__snapshots__/Anchor.spec.jsx.snap
- lib/components/BulletText/__snapshots__/BulletText.spec.jsx.snap
- lib/components/Button/Button.spec.jsx
- lib/components/CheckBox/__snapshots__/CheckBox.spec.jsx.snap
- lib/components/ColourInput/__snapshots__/ColourInput.spec.jsx.snap
- lib/components/DateInput/__snapshots__/DateInput.spec.jsx.snap
- lib/components/DatePicker/__snapshots__/DatePicker.spec.jsx.snap
- lib/components/DropDown/__snapshots__/DropDown.spec.jsx.snap
- lib/components/HorizontalAutoScroller/__snapshots__/HorizontalAutoScroller.spec.jsx.snap
- lib/components/Icon/Icon.spec.jsx
- lib/components/Icon/Icon.tsx
- lib/components/Icon/__snapshots__/Icon.spec.jsx.snap
- lib/components/Meta/__snapshots__/Meta.spec.jsx.snap
- lib/components/NumberInput/__snapshots__/NumberInput.spec.jsx.snap
- lib/components/Pagination/__snapshots__/Pagination.spec.jsx.snap
- lib/components/SelectInput/__snapshots__/SelectInput.spec.jsx.snap
- lib/components/SimplePagination/__snapshots__/SimplePagination.spec.jsx.snap
- lib/components/StandardModal/__snapshots__/StandardModal.spec.jsx.snap
- lib/components/StarRating/StarRating.spec.jsx
- lib/components/StarRating/StarRating.tsx
- lib/components/StarRating/__snapshots__/StarRating.spec.jsx.snap
- lib/components/Stepper/__snapshots__/Stepper.spec.jsx.snap
- lib/components/Table/__snapshots__/Table.spec.js.snap
- lib/components/Text/Text.tsx
- lib/components/TextInput/__snapshots__/TextInput.spec.jsx.snap
- lib/stories/helpers/index.tsx
- lib/stories/helpers/styles.css.ts
- lib/stories/icons.stories.tsx
- tweaks the html used in Icon for better accessibilty
- Adds the story for rendering all icons from @autoguru/icons
> Icon set story

- .github/workflows/buildStorybook.yml
- .github/workflows/release.yml
Only publish Storybook when release is completed
> Conditionally publish Storybook

- .changeset/two-guests-love.md
- lib/components/Button/Button.tsx
- lib/components/Button/__snapshots__/Button.spec.jsx.snap
Missing return statement when the `as` prop contained a JSX element
> Fix Button return

- .changeset/early-numbers-fry.md
- CLAUDE.md
- lib/components/AutoSuggest/AutoSuggest.spec.tsx
- lib/components/DateTimePicker/CalendarButton.tsx
- lib/components/DateTimePicker/CalendarGrid.tsx
- lib/components/DateTimePicker/DateTimePicker.css.ts
- lib/components/DateTimePicker/DateTimePicker.spec.tsx
- lib/components/OptionGrid/OptionGrid.css.ts
- lib/components/OptionGrid/OptionGrid.tsx
- lib/components/OptionList/OptionList.css.ts
- lib/components/OptionList/OptionList.spec.tsx
- lib/components/OptionList/OptionListItem.tsx
- lib/components/SearchBar/SearchBar.css.ts
- lib/components/SearchBar/SearchBar.tsx
- lib/styles/selectors.ts
- lib/utils/css.ts
This pull request introduces improvements to the `DateTimePicker`, `OptionList`, `SearchBar` and `OptionGrid` components, focusing on style consistency. Key changes include a major refactor of the styling approach to use Vanilla Extract sprinkles and CSS layers, replacement of legacy style recipes with modern patterns, and the addition of detailed unit tests for both components. Documentation has also been enhanced to clarify responsive styling and usage patterns.
**Component Styling Refactor**
* Migrated all style definitions in `DateTimePicker.css.ts` from legacy recipe-based patterns to Vanilla Extract sprinkles, ensuring consistent, theme-driven, and responsive styling. All style functions are now wrapped in the `cssLayerComponent` CSS layer for better encapsulation and …
> Beta component alignment and consistency
