autoguru-au/overdrive

- .travis.yml
- package.json
- yarn.lock
With this PR, we will strictly only release to npm with `semantic-release`. This does however bring more responsibility to the maintainers to ensure that commit messages on merges from PR's are true to the feature/docs/tests etc...
Possibly add https://github.com/commitizen/cz-cli to the mix to ensure this.
> chore: adds semantic-release

- .gitignore
- config/rollup.js
- package.json
- readme.md
- scripts/build.js
- tsconfig.json
- yarn.lock
With the PR, we will be bundling the component tree using rollup. We will generate, a cjs module, as well as an esm.
`dist/overdrive.js` => cjs
`dist/overdrive.mjs` => esm
we also run our scss through css-modules, and thus generates a `dist/overdrive.css` that will also need to be imported.
Few considerations:
> chore: build using rollup

- .travis.yml
Only run the Chromatic scripts on PR's, rather than on every Travis build event.
> ci: Only run Chromatic on PR's

- lib/components/Anchor/stories.tsx
- lib/components/Icon/index.ts
- lib/components/Icon/stories.tsx
- lib/components/Meta/stories.tsx
- lib/components/Pagination/Loading.tsx
- lib/components/Pagination/Pagination.tsx
- lib/components/SelectInput/SelectInput.tsx
- lib/components/SimplePagination/SimplePagination.tsx
- lib/components/StandardModal/StandardModal.tsx
- lib/icons/AccountBox.tsx
- lib/icons/ArrowLeft.tsx
- lib/icons/Calendar.tsx
- lib/icons/Check.tsx
- lib/icons/ChevronDown.tsx
- lib/icons/ChevronLeft.tsx
- lib/icons/ChevronRight.tsx
- lib/icons/Phone.tsx
- lib/icons/WindowClose.tsx
- lib/icons/index.ts
- scripts/buildIcons.js
I aim to expose `*Icon` components to our library consumers, so they can also use them. This has needed me to rename `Account` (icon) to be `AccountIcon` so there are no re-export conflicts. 
In the future this could maybe be done again with a seperate bundle this project could expose, eg:
```tsx
import { Icon } from '@autoguru/overdrive';
import { Account } from '@autoguru/overdrive/icons';
<Icon icon={Account}/>
```
> feat(Icon): Expose *Icon components

- lib/components/StarRating/StarRating.spec.jsx
- lib/components/StarRating/StarRating.tsx
- lib/components/StarRating/stories.tsx
With this PR I aim to address the pointlessly long prop `ratingValue`, and move to simply `rating`.
There is a backward support there, for with a console warn. This will be removed in future releases.
Seeing as the snapshot file for this component, is untouched, you can guarantee that there is no material change to the component itself.
> feat(StarRating): Moved to the rating prop

- lib/components/Anchor/Anchor.spec.jsx
- lib/components/Anchor/Anchor.tsx
- lib/components/Anchor/__snapshots__/Anchor.spec.jsx.snap
- lib/components/Anchor/stories.tsx
- lib/components/Button/Button.spec.jsx
- lib/components/Button/Button.tsx
- lib/components/Button/stories.tsx
Migration of `component={}` props to the new `is={}` prop, this is backward compatible, but pending a future removal.
> feat: Using new `is` prop instead of `component`

- lib/components/Anchor/__snapshots__/Anchor.spec.jsx.snap
- lib/components/Button/Button.tsx
- lib/components/Button/style.scss
With this PR I aim to address 2 things, but mainly the addition of the `ref={}` prop to our `Buttons`, to allow us to access the "root" element of the Button, granted this is now a contract with this component, so comments here would be nice. And secondly, the `scale(1)`, so when we translate up, we don't blur the contents of the button.
> feat(Button): Ref-forward to the "root" element

- lib/components/Stepper/Stepper.tsx
The purpose of this PR is to fix the excessive render cycles caused by usage os useState hook to remember the previous value of the stepper component.
> fix(Stepper): Uses useRef rather than useState to memoize previous value

- lib/components/DateInput/DateInput.tsx
- lib/components/DateInput/stories.tsx
- lib/components/InputBase/withEnhancedInput.tsx
- lib/components/NumberInput/NumberInput.tsx
- lib/components/NumberInput/__snapshots__/NumberInput.spec.jsx.snap
- lib/components/SelectInput/SelectInput.tsx
- lib/components/SelectInput/__snapshots__/SelectInput.spec.jsx.snap
- lib/components/TextAreaInput/TextAreaInput.spec.jsx
- lib/components/TextAreaInput/TextAreaInput.tsx
- lib/components/TextAreaInput/__snapshots__/TextAreaInput.spec.jsx.snap
- lib/components/TextInput/TextInput.tsx
- lib/components/TextInput/__snapshots__/TextInput.spec.jsx.snap
With this PR I aim to address the webkit clear button that clears date input values - this is a temporary solution until we implement a bespoke date picker.
> fix(InputBase): Clear date no longer breaks ui

- lib/components/ModalBase/style.scss
- lib/components/StandardModal/style.scss
This PR allows backdrops to be clickable "tap-able" to request a closure.
> fix(ModalBase): Backdrop taps now trigger on small viewports

- lib/components/Typography/TextLink/TextLink.scss
- lib/components/Typography/TextLink/TextLink.tsx
- lib/components/Typography/TextLink/__snapshots__/TextLink.spec.jsx.snap
- lib/components/Typography/TextLink/stories.tsx
With this PR I aim to bring anchors back into flow, which essentially alleviates the need for position: absolute
> feat(TextLink): Hover states with inset shadow instead

- lib/components/ModalBase/ModalPortal.tsx
- lib/components/OutsideClick/OutsideClick.spec.jsx
- lib/components/OutsideClick/OutsideClick.tsx
- lib/components/OutsideClick/index.ts
- lib/components/OutsideClick/stories.tsx
- lib/components/Positioner/Positioner.tsx
- lib/components/Positioner/stories.tsx
- lib/components/index.ts
With this PR I introduce a new component and hook:
- `useOutsideClick` which takes an array of refObjects, and a callback to fire when a click happens outside of those refs
- `<OutsideClick>` which requires exactly 1 child, and an `onOutsideClick` prop. This component is used for when you don't care about using the ref of the child itself. This will cloneElement. 🤷🏼‍♂️
> feat(OutsideClick): OutsideClick exposed as a utility component

- lib/components/Positioner/Positioner.tsx
This will expose a triggerOffset prop that will allow the flyout or alike to define its own offset from the trigger when calculations occur.
> feat(Positioner): Enable triggerOffset overriding

- lib/components/DateInput/DateInput.tsx
- lib/components/InputBase/withEnhancedInput.tsx
- lib/components/NumberInput/NumberInput.tsx
- lib/components/SelectInput/SelectInput.tsx
- lib/components/TextAreaInput/TextAreaInput.tsx
- lib/components/TextInput/TextInput.tsx
With this event handlers will be type safe. React onChange handlers, dont have type information of them at the Element level, only at the attribute point. Which is why we have the EventHandler type and pass in the type. It would be a decision we'd need to make, if we pass in the `typescript:dom/HTML*Element` type, and construct the events ourselves, or if we pass in a `react/InputHTMLAttributes<typescript:dom/HTMLInputElement>` type, which we could then `Pick`. 
React:DOMAttributes, which will allow a Pick, has incorrect types for onChange. So something like wouldnt work:
```
interface EventHandlers<PrimitiveElementType> extends Pick<DOMAttributes<PrimitiveElementType>, 'onChange' |
'onBlur' |
'onFocus' |
'onKeyDown'> {
}
```
Working example:
> Notice how `target` knows its an input html …
> feat(withEnhancedInput): Type safe events types

- lib/components/AutoSuggest/AutoSuggest.scss
- lib/components/StandardModal/style.scss
Albeit still in draft this feature will be very likely to make its way into the spec - and is currently supported by all major browsers we care about.
https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior
> feat: Utilise new scroll contain css property

- lib/components/Alert/Alert.scss
- lib/components/Toaster/Toaster.scss
- lib/components/Toaster/index.ts
- lib/components/Toaster/stories.tsx
- lib/components/Toaster/toast.spec.js
- lib/components/Toaster/toast.tsx
- lib/components/index.ts
The idea is to simply import `import { toast } from '@autoguru/overdrive';` and by calling that method, you get a toast to appear on the screen. And without needing to wire up a collector component.
> feat(Toaster): Init impl of a notification manager component

- lib/components/AutoSuggest/AutoSuggest.tsx
By not enforcing autofocus on fullscreen AutoSuggest view, the consumer will have a chance to to automatically open virtual keyboard
> feat: Removes forced autosuggest from fullscreen autosuggest

- .changeset/serious-cobras-sleep.md
- lib/components/Alert/__snapshots__/Alert.spec.jsx.snap
- lib/components/Button/__snapshots__/Button.spec.jsx.snap
- lib/components/Pagination/__snapshots__/Pagination.spec.jsx.snap
- lib/components/SimplePagination/__snapshots__/SimplePagination.spec.jsx.snap
- lib/components/Stepper/__snapshots__/Stepper.spec.jsx.snap
- lib/components/Tabs/__snapshots__/Tabs.spec.jsx.snap
- lib/components/Typography/Anchor/__snapshots__/Anchor.spec.jsx.snap
- lib/components/Typography/TextLink/__snapshots__/TextLink.spec.jsx.snap
- lib/reset/reset.treat.ts
Seeing as we use `<TextLink />` or `<Box is="a" href="" />` in a few places, it only makes sense to use `a { cursor: pointer }`.
> feat: Anchors are now cursor pointer by default

- .changeset/tall-ravens-double.md
- lib/components/Inline/Inline.treat.ts
- lib/components/Inline/Inline.tsx
- lib/components/StarRating/StarRating.treat.ts
- lib/components/StarRating/StarRating.tsx
**FEATURES**
**`<Inline />`**
Now supports an alignY responsive prop to vertically center its items to either `top | center | bottom`, eg: `<Inline alignY="center">`
**`<StarRating />`**
Uses the `<Inline />` component instead of columns, so should use less DOM
> feat: Inline alignY prop

- .changeset/clean-tomatoes-leave.md
- lib/components/Tabs/TabList.tsx
- lib/components/Tabs/Tabs.treat.ts
- lib/components/Tabs/__snapshots__/Tabs.spec.jsx.snap
- lib/components/Tabs/stories.tsx
**FEATURES**
**`<TabList />`**
In small contexts, like sidebars, or mobile viewports with minimal tablist items. It makes sense to stretch items to meet the width of the container.
eg:
```
<Tabs>
<TabList stretch>
<Tab>Tab a</Tab>
<Tab>Tab b</Tab>
</TabList>
</Tabs>
```
---
[Playroom example](https://overdrive--616fd3a619b2285b3d37b6dca9e2bbf439923bd9.surge.sh/playroom/#?code=N4Igxg9gJgpiBcIA8BlGYAuBLCA7ABAA4CGUUWuA5gBoC8AOiAMyMB89B+SAKsQEYBndp3xdefADJYBGfDIBOMDGAAWw0RrH9WABRi5yVJAHpx6zVr74K5MMWx5awJgF9WAeQBuMeVHkBXGBMzDgtLawMsOwdcJwBGOLcAYQgAW0IAGyUYKGDtUI08yWkMcyKhDhM0TBxcYRAXIA)
> feat(Tabs): Support stretching tablist items

- .changeset/tender-apes-sniff.md
- lib/components/AutoSuggest/AutoSuggest.tsx
AutoSuggest: Support the usage of passing a ref down to the implemented input
**FEATURES**
`<AutoSuggest>` can now be given a ref which will be passed down to the
underlying input.
eg:
```tsx
const myRef = useRef<HTMLInputElement | null>(null);
<AutoSuggest ref={myRef} value={null} placeholder={'My AutoSuggest'} />;
```
> feat(AutoSuggest): Support forwardRef for AutoSuggest inputs

- .changeset/shiny-rabbits-teach.md
- lib/components/AutoSuggest/AutoSuggest.tsx
AutoSuggest: Introduce a autoWidth prop that either will size the flyout to
either the width of the children, or the input.
**FEATURES**
`<AutoSuggest>` can now be given a `autoWidth` prop that will auto the width in
relation to setting the width, or for it to be automatic.
-   `autoWidth={true}` means, size the flyout to the width of flyout children
"automatically"
-   `autoWidth={false}` means to set to the width of the select input.
eg:
```jsx
// size to the width of the flyout children
<AutoSuggest
placeholder="How are you?"
suggestions={[{ text: "Im an item" }]}
autoWidth
/>
// size to the width of the input (current behaviour)
<AutoSuggest
placeholder="How are you?"
suggestions={[{ text: "Im an item" }]}
/>
```
----
[Playroom …
> feat(AutoSuggest): Introduce an autoWidth prop to size the flyout

- .changeset/good-elephants-study.md
- lib/components/Box/Box.tsx
- lib/components/Box/useBoxStyles.treat.ts
- lib/components/Box/useBoxStyles.ts
Box: Adds an overflow prop and allows className to be clsx compatible
**FEATURES**
`ClassName` can now be sent in directly to Box instead of through clsx.
eg.
```diff
- <Box className={clsx(styles.one, styles.two)}>
+ <Box className={[styles.one, styles.two]}>
Hello
</Box>
- <Box className={clsx({[styles.one]: maybeDoMe}, styles.two)}>
+ <Box className={[{[styles.one]: maybeDoMe}, styles.two]}>
Hello
</Box>
```
> feat(Box): Introduces overflow and passing in clsx compat prop

- .changeset/breezy-horses-smoke.md
- lib/components/DateInput/__snapshots__/DateInput.spec.jsx.snap
- lib/components/InputBase/NotchedBase.treat.ts
- lib/components/InputBase/NotchedBase.tsx
- lib/components/InputBase/__snapshots__/NotchedBase.spec.jsx.snap
- lib/components/InputBase/withEnhancedInput.treat.ts
- lib/components/InputBase/withEnhancedInput.tsx
- lib/components/NumberInput/__snapshots__/NumberInput.spec.jsx.snap
- lib/components/SelectInput/__snapshots__/SelectInput.spec.jsx.snap
- lib/components/TextAreaInput/__snapshots__/TextAreaInput.spec.jsx.snap
- lib/components/TextInput/__snapshots__/TextInput.spec.jsx.snap
InputBase: Allow for notchless inputs
**FEATURES**
Sometimes the notch behaviour won't work because of its context - much like an
input that sits within a table, where the column already denotes what should be
entered into the input.
> Please be aware that this should be avoided, as in most cases we should notch,
> so a user knows what's in the input especially when its defaulted.
[View here](https://overdrive--92aea34e2ec168bf86126605c943d7c1231c9622.surge.sh/playroom/#?code=N4Igxg9gJgpiBcIA8AhCAPABABwIZSgEsA7AcwF4AdEAFmoD5LjNMkBlAF1zAGtMBnPGBIVqdEI2YtWAFRjoOASWLYArhxwAbbjAAWETbABOVEAAkIAd0y4jMTAE8IqgPzVMxCBzC7ywAGa4mvwwAL6YAPSS0rLySirqWjr6hjAm1BbWtvZOru5RTDFIcgrKahrY2mB6BsammTZ2js5uIB5ePn6BwWGYAG5BqjD1MJqaEPnR0sVxZYmVybVp9VaNOS3uA5pDI2MTbQVSSBGc3DySx2jokiChQA)
---
Technical:
- I fall …
> feat(InputBase): Allows for notchless inputs

- .changeset/young-taxis-poke.md
- lib/components/Actions/Actions.tsx
- lib/components/Columns/Column.tsx
- lib/components/Inline/Inline.tsx
- lib/components/Stack/Stack.spec.jsx
- lib/components/Stack/Stack.tsx
- lib/components/Stack/__snapshots__/Stack.spec.jsx.snap
- lib/components/Tabs/TabList.tsx
- lib/components/Tabs/TabPanes.tsx
- package.json
- yarn.lock
Flatten fragments when provided as children
Will now support fragments and otherwise boolean children that previously would
not have worked:
```jsx
<Stack>
<p>line 0</p>
{isEnabled && (
<>
<p>Line 1</p>
<p>Line 2</p>
<p>Line 3</p>
</>
)}
<p>line 4</p>
</Stack>
```
> which would have the past not had lines 1-3 spaced evenly.
this was also true for: `Actions`, `Inline`, `TabList`, `TabPanes` and `Stack`.
Which have been rectified.
> feat: Flatten fragments when provided as children

- .changeset/tender-adults-yawn.md
- lib/components/DateInput/__snapshots__/DateInput.spec.jsx.snap
- lib/components/InputBase/withEnhancedInput.treat.ts
- lib/components/InputBase/withEnhancedInput.tsx
- lib/components/NumberInput/__snapshots__/NumberInput.spec.jsx.snap
- lib/components/SelectInput/__snapshots__/SelectInput.spec.jsx.snap
- lib/components/TextAreaInput/__snapshots__/TextAreaInput.spec.jsx.snap
- lib/components/TextInput/__snapshots__/TextInput.spec.jsx.snap
Notchless inputs will no longer break when part of a flex container
---
Reproduction
```jsx
<Columns width="full">
<Column grow>
<TextInput name="test" placeholder="test" ></TextInput>
</Column>
</Columns>
```
> fix(InputBase): Fullwidth the input wrapper

- .changeset/itchy-days-marry.md
- lib/components/ProgressBar/stories.tsx
- lib/components/Stack/Stack.tsx
- lib/components/Stack/stories.tsx
- lib/components/TextContainer/TextContainer.tsx
This is to get some consistency between our `<Columns />` component and this, in that both use the concept of space, but called differently.
This is a breaking change, but I do believe it's a simple activity to go find-replace. I'm working on a jscodeshift for stuff like this in the future. 
---
A Renamed prop from spacing to space
eg:
```diff
<Stack is="ul"
-    spacing="3">
+    space="3">
<li>line 1</li>
<li>line 2</li>
<li>line 3</li>
</Stack>
```
> feat(Stack): Renamed spacing prop to space

- .changeset/short-cherries-push.md
- lib/components/Typography/Text/Text.tsx
- lib/components/Typography/Text/useTextStyles.treat.ts
- lib/components/Typography/Text/useTextStyles.ts
As mentioned in the changeset - I'm not 100% convinced in the change here. It'll inadvertently mean that text need to be a block-like element now. Meaning this will only work on `<Text is="p" />`. But will release, and see how we go using it. So the API _might_ change.
For now, lets consume this PR directly internally and dog-food for a bit.
```
"@autoguru/overdrive": "autoguru-au/overdrive#no-wrap-text"
```
> package.json
---
Text: Exposes a new white-space nowrap prop
This is an **experimental** prop, we know of one use-case where this can be
used, but will likely also appear on the Box.
So do let us know if you're using this, and it hasnt worked in your use-case.
**FEATURES**
You can now pass a `noWrap` prop to any `<Text />` which applies a
`white-space: nowrap` to itself.
```jsx …
```
> feat(Text): Supports a noWrap prop to not wrap its content

- .changeset/yellow-snails-play.md
- lib/components/Box/Box.tsx
- lib/components/Box/useBoxStyles.treat.ts
- lib/components/Box/useBoxStyles.ts
Box: Introduces flex style props to `Box` and `useBoxStyles`
**FEATURES**
You can now send in `alignItems`,`flexDirection`, `flexGrow`, `flexShrink`, `flexWrap`, `justifyContent` to Box and useBoxStyles for whatever you like.
We have specifically chosen `alignItems`, `flexDirection`, `justifyContent` as Responsive candidates as we've found the others won't have a responsive use case.
```jsx
<Box display="flex" width="full" justifyContent="center">
<Button>Hello</Button>
</Box>
```
> feat(Box): Introduce flex style props to box/useBox

- .changeset/metal-sloths-call.md
- packages/overdrive/lib/components/SelectInput/SelectInput.treat.ts
- packages/overdrive/lib/components/SelectInput/SelectInput.tsx
- packages/overdrive/lib/components/SelectInput/__snapshots__/SelectInput.spec.jsx.snap
With this change SelectInput component stretches native select element to cover full with on the component. With this change the arrow down icon becomes an absolutely positioned element with no pointer events and select input gets additional left padding to reserve the arrow down icon area
> feat: Increases select input click area to cover full component width

- .changeset/flat-candles-nail.md
- packages/overdrive/lib/components/Badge/Badge.treat.ts
- packages/overdrive/lib/components/Badge/Badge.tsx
- packages/overdrive/lib/components/Badge/__snapshots__/Badge.spec.jsx.snap
This PR fixes inverted badge colour being overridden with the default colour introduced by the useTextStyles hook
> fix: Fixes inverted badge text colour

- .changeset/red-crabs-tease.md
- packages/overdrive/lib/components/Badge/Badge.treat.ts
- packages/overdrive/lib/components/Badge/Badge.tsx
- packages/overdrive/lib/components/Badge/__snapshots__/Badge.spec.jsx.snap
This PR fixes incorrect default badge text styles caused by wrong ordering caused by [/pull/545]
> fix: Badge to use text style as source

- .changeset/thirty-plants-pull.md
- packages/overdrive/lib/themes/base/tokens.ts
- packages/overdrive/lib/themes/tokens.ts
This PR adds a new 'small' option to Section component. A typical use-case for this new width is when a page displays a small amount of text content causing single lines when inside medium or large section widths.
> feat: Introduces a new small option for width values

- .changeset/chatty-rice-play.md
- packages/overdrive/lib/components/StandardModal/StandardModal.treat.ts
This PR make two changes to the standard modal
1. Ensures the mobile view always has modal pinned to the bottom of the page
2. In tablet view rounds all corners to be consistent with desktop view
> feat: StandardModal mobile and tablet view fix

- .changeset/cool-waves-cheer.md
- packages/overdrive/lib/components/Stepper/Stepper.tsx
Currently Stepper component reacts to change of value prop coming in as a result on internal onChange trigger. This change skips reducer dispatch if incoming value and internal state are the same.
> fix(Stepper): No longer re-render when incoming change happens

- .changeset/healthy-singers-trade.md
- packages/overdrive/lib/components/CheckBox/CheckBox.tsx
- packages/overdrive/lib/components/Radio/Radio.tsx
- packages/overdrive/lib/components/Radio/RadioGroup.tsx
- packages/overdrive/lib/components/private/CheckableBase/CheckableBase.tsx
In order to facilitate Radio and CheckBoxes to be integrated with form management libraries such as Formik, we need to be bale to pas element refs down to input elements.
> feat: Adds forwardRef to all checkables

- .changeset/chilly-bees-grin.md
- lib/components/Heading/Heading.tsx
- lib/components/Text/Text.tsx
This pull request introduces new `id` and `testId` props to the `Text` and `Heading` components to improve their testability and identification. Below are the most important changes:
* Added `id` and `testId` props to the `Text` component in `lib/components/Text/Text.tsx`. [[1]](diffhunk://#diff-72cccd06911d8e3be548ce966954bdc790ddc9eba76f89eb07124d2b5cadb7daR13-R14) [[2]](diffhunk://#diff-72cccd06911d8e3be548ce966954bdc790ddc9eba76f89eb07124d2b5cadb7daR30-R31) [[3]](diffhunk://#diff-72cccd06911d8e3be548ce966954bdc790ddc9eba76f89eb07124d2b5cadb7daR47-R48)
* Added `id` and `testId` props to the `Heading` component in `lib/components/Heading/Heading.tsx`. [[1]](diffhunk://#diff-7cd45168261448f3423b0b0921f941f726bf9954928382635e8bfbce59a1c71eR16-R17) …
> feat: Adds id and test id props to text and headings

- .github/workflows/ci.yml
`ci` workflow will ignore the `changeset-release` branches to avoid Chromatic hang
> Change publish CI behaviour

- .github/workflows/ci.yml
- lib/components/AutoSuggest/AutoSuggest.stories.tsx
- lib/components/Badge/Badge.stories.tsx
- lib/components/CheckBox/CheckBox.stories.tsx
- lib/components/ColourInput/ColourInput.stories.tsx
- lib/components/DateInput/DateInput.stories.tsx
- lib/components/DatePicker/DatePicker.stories.tsx
- lib/components/IntentStripe/IntentStripe.stories.tsx
- lib/components/NumberInput/NumberInput.stories.tsx
- lib/components/Pagination/Pagination.stories.tsx
- lib/components/Radio/Radio.stories.tsx
- lib/components/SelectInput/SelectInput.stories.tsx
- lib/components/Tabs/Tabs.stories.tsx
- lib/components/TextAreaInput/TextAreaInput.stories.tsx
- lib/components/TextContainer/TextContainer.stories.tsx
- lib/components/TextInput/TextInput.stories.tsx
- lib/components/Tooltip/Tooltip.stories.tsx
- removes a number of less valuable stories from Storybook, reducing the total number of stories by 23%
- skips Chromatic for several scenarios including pushing without a PR, pushing with a PR in draft mode, and for all `changeset-release` branches
> Reduce Chromatic usage

- eslint.config.mjs
- lib/components/CheckBox/CheckBox.css.ts
- lib/components/CheckBox/CheckBox.stories.tsx
- lib/components/CheckBox/CheckBox.tsx
Introduce an indeterminate state for checkboxes, allowing for better representation of partial selections. Update stories to demonstrate the new functionality.
> Checkbox indeterminate state

- .github/workflows/buildStorybook.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
This pull request restructures workflows to use a common setup node version setup pattern.
It enables the `setup-node` inbuilt caching and converts deprecated set-output commands to GITHUB_OUTPUT.
> Enable caching in GH workflows

- .changeset/rotten-spoons-beg.md
- lib/components/AutoSuggest/AutoSuggest.tsx
- lib/components/Box/useBox.ts
- lib/components/BulletList/Bullet.tsx
- lib/components/BulletList/BulletList.tsx
- lib/components/BulletList/__snapshots__/Bullet.spec.jsx.snap
- lib/components/BulletList/__snapshots__/BulletList.spec.jsx.snap
- lib/components/DropDown/DropDownOption.tsx
- lib/components/LinearProgressIndicator/LinearProgressIndicator.tsx
- lib/components/LinearProgressIndicator/__snapshots__/LinearProgressIndicator.spec.jsx.snap
- lib/components/LoadingBox/LoadingBox.tsx
The `is` attribute was allowed because of inherited html attributes
> Ensure `is` prop is disallowed on Box

- .changeset/shiny-readers-own.md
- .changeset/tall-dogs-rhyme.md
- lib/components/AutoSuggest/AutoSuggest.tsx
- lib/components/BulletText/BulletText.tsx
- lib/components/ColourInput/ColourInput.tsx
- lib/components/Columns/Column.css.ts
- lib/components/Columns/Column.tsx
- lib/components/Columns/Columns.stories.tsx
- lib/components/DateTimePicker/DateTimePicker.tsx
- lib/components/HorizontalAutoScroller/HorizontalAutoScroller.tsx
- lib/components/MinimalModal/MinimalModal.tsx
- lib/components/MinimalModal/__snapshots__/MinimalModal.spec.jsx.snap
- lib/components/OptionGrid/OptionGrid.css.ts
- lib/components/OptionList/OptionList.css.ts
- lib/components/SelectInput/SelectInput.tsx
- lib/components/StandardModal/StandardModal.tsx
- lib/stories/shared/argTypes-box.ts
- lib/styles/sprinkles.css.ts
- package.json
- yarn.lock
Solves typechecking issue in MFEs by ensuring that sprinkles is a peer dependency of Overdrive.
Customise the `alignSelf` prop on Column to match existing usage.
Also improves the prop autocomplete for sprinkles style props that were numerical by converting to string union.
> 4.43 patch: @vanilla-extract/sprinkles peer dependency

- .changeset/true-berries-fall.md
- lib/components/Tabs/Tab.css.ts
- lib/components/Tabs/TabList.css.ts
- lib/components/Tabs/Tabs.tsx
- lib/components/Tabs/__snapshots__/Tabs.spec.jsx.snap
This pull request introduces a new `minimal` appearance setting for the `Tabs` component in the `@autoguru/overdrive` package. The changes include updates to styling, type definitions, and tests to support this new appearance variant.
* Added a `minimal` appearance variant to the `Tabs` component, including new styles for inactive and active states, as well as spacing between tabs. (`lib/components/Tabs/Tab.css.ts`: [[1]](diffhunk://#diff-787547fa80265722c88654dfb8e977c86712421a2134ac5338ee18dd066383c5R46-R54) [[2]](diffhunk://#diff-787547fa80265722c88654dfb8e977c86712421a2134ac5338ee18dd066383c5R82-R91)
* Updated the `TabList` component to recognize the `minimal` appearance. (`lib/components/Tabs/TabList.css.ts`: [lib/components/Tabs/TabList.css.tsR14](diffhunk://#diff-610cbbcf4128eeecb74 …
> patch: adds `minimal` appearance to Tabs
